var textos_ES = {
    // textos generales
    'text_titulo_app': 'Interfaz ET2 IU',
    'text_titulo_menu': 'Opciones del menú',
    'label_seleccioncolumnas': 'Seleccionar columnas',
    'RECORDSET_VACIO': 'No hay coincidencias para la búsqueda',

    // menú
    'menu_alumnograduacion': 'Alumnado en Graduación',
    'menu_articulo': 'Artículos científicos',
    'menu_ubicacion': 'Ubicaciones de sitios',

    // títulos de páginas y formularios alumnograduacion
    'text_titulo_page_alumnograduacion': 'Gestión de Alumnos en Graduación',
    'text_contenido_titulo_form_alumnograduacion_ADD': 'Alta de alumno en graduación',
    'text_contenido_titulo_form_alumnograduacion_EDIT': 'Modificación de alumno en graduación',
    'text_contenido_titulo_form_alumnograduacion_DELETE': 'Eliminación de alumno en graduación',
    'text_contenido_titulo_form_alumnograduacion_SHOWCURRENT': 'Detalle de alumno en graduación',
    'text_contenido_titulo_form_alumnograduacion_SEARCH': 'Búsqueda de alumnos en graduación',

    // etiquetas alumnograduacion
    'label_dni_alumno': 'DNI del alumno',
    'label_cod_titulacion': 'Código de titulación',
    'label_nombre_trabajo': 'Título del trabajo',
    'label_anio_academico': 'Curso académico',
    'label_nota_final': 'Nota final',
    'label_tutor_principal': 'Tutor principal',
    'label_fecha_defensa': 'Fecha de defensa',
    'label_memoria_pdf': 'Memoria presentada',
    'label_nuevo_memoria_pdf': 'Memoria (fichero PDF)',

    // mensajes error alumnograduacion
    'dni_alumno_min_size_KO': 'El DNI debe contener 9 caracteres.',
    'dni_alumno_max_size_KO': 'El DNI debe contener exactamente 9 caracteres.',
    'dni_alumno_format_KO': 'El formato del DNI no es válido.',
    'dni_alumno_letter_KO': 'La letra del DNI no es correcta.',
    'cod_titulacion_min_size_KO': 'El código de titulación debe tener al menos 3 caracteres.',
    'cod_titulacion_max_size_KO': 'El código de titulación no puede superar los 10 caracteres.',
    'cod_titulacion_format_KO': 'El código de titulación solo puede contener letras mayúsculas y números.',
    'nombre_trabajo_min_size_KO': 'El título del trabajo debe tener al menos 5 caracteres.',
    'nombre_trabajo_max_size_KO': 'El título del trabajo no puede superar los 100 caracteres.',
    'nombre_trabajo_format_KO': 'El título del trabajo solo puede contener letras, números y signos básicos.',
    'anio_academico_format_KO': 'El curso académico debe tener el formato AAAA-AAAA.',
    'anio_academico_range_KO': 'El curso académico final debe ser el siguiente al inicial.',
    'nota_final_format_KO': 'La nota debe ser un número con hasta dos decimales.',
    'nota_final_range_KO': 'La nota debe estar entre 0 y 10.',
    'tutor_principal_min_size_KO': 'El tutor debe tener al menos 4 caracteres.',
    'tutor_principal_max_size_KO': 'El tutor no puede superar los 60 caracteres.',
    'tutor_principal_format_KO': 'El tutor solo puede contener letras y espacios.',
    'fecha_defensa_format_KO': 'La fecha debe tener el formato dd/mm/aaaa.',
    'fecha_defensa_value_KO': 'La fecha indicada no es válida.',
    'nuevo_memoria_pdf_not_exist_file_KO': 'Debe adjuntar el fichero de la memoria.',
    'nuevo_memoria_pdf_type_file_KO': 'La memoria debe ser un PDF.',
    'nuevo_memoria_pdf_max_size_file_KO': 'El fichero de memoria supera el tamaño permitido (5MB).',
    'nuevo_memoria_pdf_format_name_file_KO': 'El nombre del fichero solo puede contener letras, números, guiones y puntos.',

    // títulos de páginas y formularios articulo
    'text_titulo_page_articulo': 'Gestión de artículos científicos',
    'text_contenido_titulo_form_articulo_ADD': 'Alta de artículo',
    'text_contenido_titulo_form_articulo_EDIT': 'Modificación de artículo',
    'text_contenido_titulo_form_articulo_DELETE': 'Eliminación de artículo',
    'text_contenido_titulo_form_articulo_SHOWCURRENT': 'Detalle de artículo',
    'text_contenido_titulo_form_articulo_SEARCH': 'Búsqueda de artículos',

    // etiquetas articulo
    'label_CodigoA': 'Código del artículo',
    'label_AutoresA': 'Autores',
    'label_TituloA': 'Título del artículo',
    'label_TituloR': 'Título de la revista',
    'label_ISSN': 'ISSN',
    'label_VolumenR': 'Volumen',
    'label_PagIniA': 'Página inicial',
    'label_PagFinA': 'Página final',
    'label_FechaPublicacionR': 'Fecha de publicación',
    'label_FicheropdfA': 'Fichero PDF',
    'label_nuevo_FicheropdfA': 'Fichero PDF (subida)',
    'label_EstadoA': 'Estado de tramitación',

    // errores articulo
    'CodigoA_min_size_KO': 'El código del artículo es obligatorio.',
    'CodigoA_format_KO': 'El código del artículo solo puede contener números.',
    'AutoresA_min_size_KO': 'Debe indicar al menos un autor.',
    'AutoresA_max_size_KO': 'La lista de autores no puede superar los 200 caracteres.',
    'AutoresA_format_KO': 'Los autores solo pueden contener letras, espacios, comas y puntos.',
    'TituloA_min_size_KO': 'El título del artículo es obligatorio.',
    'TituloA_max_size_KO': 'El título del artículo no puede superar los 100 caracteres.',
    'TituloA_format_KO': 'El título del artículo contiene caracteres no permitidos.',
    'TituloR_min_size_KO': 'El título de la revista es obligatorio.',
    'TituloR_max_size_KO': 'El título de la revista no puede superar los 100 caracteres.',
    'TituloR_format_KO': 'El título de la revista contiene caracteres no permitidos.',
    'ISSN_min_size_KO': 'El ISSN debe tener 9 caracteres.',
    'ISSN_format_KO': 'El ISSN debe seguir el formato 0000-000X.',
    'VolumenR_min_size_KO': 'Debe indicar el volumen de la revista.',
    'VolumenR_format_KO': 'El volumen solo puede contener números (máximo 4 dígitos).',
    'PagIniA_min_size_KO': 'Debe indicar la página inicial.',
    'PagIniA_format_KO': 'La página inicial solo puede contener números.',
    'PagFinA_min_size_KO': 'Debe indicar la página final.',
    'PagFinA_format_KO': 'La página final solo puede contener números.',
    'PagFinA_range_KO': 'La página final debe ser mayor o igual que la inicial.',
    'FechaPublicacionR_format_KO': 'La fecha debe tener el formato dd/mm/aaaa.',
    'FechaPublicacionR_value_KO': 'La fecha indicada no es válida.',
    'EstadoA_value_KO': 'Debe seleccionar un estado válido.',
    'nuevo_FicheropdfA_not_exist_file_KO': 'Debe adjuntar el PDF del artículo.',
    'nuevo_FicheropdfA_type_file_KO': 'El fichero del artículo debe ser un PDF.',
    'nuevo_FicheropdfA_max_size_file_KO': 'El fichero del artículo supera el tamaño permitido (5MB).',
    'nuevo_FicheropdfA_format_name_file_KO': 'El nombre del fichero solo puede contener letras, números, guiones y puntos.',

    // títulos de páginas y formularios ubicacion
    'text_titulo_page_ubicacion': 'Gestión de sitios de medida',
    'text_contenido_titulo_form_ubicacion_ADD': 'Alta de sitio',
    'text_contenido_titulo_form_ubicacion_EDIT': 'Modificación de sitio',
    'text_contenido_titulo_form_ubicacion_DELETE': 'Eliminación de sitio',
    'text_contenido_titulo_form_ubicacion_SHOWCURRENT': 'Detalle de sitio',
    'text_contenido_titulo_form_ubicacion_SEARCH': 'Búsqueda de sitios',

    // etiquetas ubicacion
    'label_id_site': 'Identificador',
    'label_site_latitud': 'Latitud (WGS84)',
    'label_site_longitud': 'Longitud (WGS84)',
    'label_site_altitude': 'Altitud (m)',
    'label_site_locality': 'Localidad',
    'label_site_provider_login': 'Login del proveedor',
    'label_site_north_photo': 'Foto hacia el norte',
    'label_site_south_photo': 'Foto hacia el sur',
    'label_site_east_photo': 'Foto hacia el este',
    'label_site_west_photo': 'Foto hacia el oeste',
    'label_nuevo_site_north_photo': 'Subir foto norte',
    'label_nuevo_site_south_photo': 'Subir foto sur',
    'label_nuevo_site_east_photo': 'Subir foto este',
    'label_nuevo_site_west_photo': 'Subir foto oeste',

    // errores ubicacion
    'id_site_format_KO': 'El identificador debe ser numérico.',
    'site_latitud_format_KO': 'La latitud debe tener formato decimal con hasta seis decimales.',
    'site_latitud_range_KO': 'La latitud debe estar entre -90 y 90 grados.',
    'site_longitud_format_KO': 'La longitud debe tener formato decimal con hasta seis decimales.',
    'site_longitud_range_KO': 'La longitud debe estar entre -180 y 180 grados.',
    'site_altitude_format_KO': 'La altitud debe ser un número entero.',
    'site_altitude_range_KO': 'La altitud debe estar entre -500 y 9000 metros.',
    'site_locality_min_size_KO': 'La localidad debe tener al menos 3 caracteres.',
    'site_locality_max_size_KO': 'La localidad no puede superar los 40 caracteres.',
    'site_locality_format_KO': 'La localidad solo puede contener letras, espacios y guiones.',
    'site_provider_login_min_size_KO': 'El login debe tener al menos 3 caracteres.',
    'site_provider_login_max_size_KO': 'El login no puede superar los 30 caracteres.',
    'site_provider_login_format_KO': 'El login solo puede contener letras, números, guiones y guiones bajos.',
    'nuevo_site_north_photo_not_exist_file_KO': 'Debe adjuntar la foto hacia el norte.',
    'nuevo_site_north_photo_type_file_KO': 'La foto norte debe ser JPG o PNG.',
    'nuevo_site_north_photo_max_size_file_KO': 'La foto norte supera el tamaño permitido (5MB).',
    'nuevo_site_north_photo_format_name_file_KO': 'El nombre de la foto norte solo puede contener letras, números, guiones y puntos.',
    'nuevo_site_south_photo_not_exist_file_KO': 'Debe adjuntar la foto hacia el sur.',
    'nuevo_site_south_photo_type_file_KO': 'La foto sur debe ser JPG o PNG.',
    'nuevo_site_south_photo_max_size_file_KO': 'La foto sur supera el tamaño permitido (5MB).',
    'nuevo_site_south_photo_format_name_file_KO': 'El nombre de la foto sur solo puede contener letras, números, guiones y puntos.',
    'nuevo_site_east_photo_not_exist_file_KO': 'Debe adjuntar la foto hacia el este.',
    'nuevo_site_east_photo_type_file_KO': 'La foto este debe ser JPG o PNG.',
    'nuevo_site_east_photo_max_size_file_KO': 'La foto este supera el tamaño permitido (5MB).',
    'nuevo_site_east_photo_format_name_file_KO': 'El nombre de la foto este solo puede contener letras, números, guiones y puntos.',
    'nuevo_site_west_photo_not_exist_file_KO': 'Debe adjuntar la foto hacia el oeste.',
    'nuevo_site_west_photo_type_file_KO': 'La foto oeste debe ser JPG o PNG.',
    'nuevo_site_west_photo_max_size_file_KO': 'La foto oeste supera el tamaño permitido (5MB).',
    'nuevo_site_west_photo_format_name_file_KO': 'El nombre de la foto oeste solo puede contener letras, números, guiones y puntos.'
};
