var textos_EN = {
    'text_titulo_app': 'ET2 UI Interface',
    'text_titulo_menu': 'Menu options',
    'label_seleccioncolumnas': 'Select columns',
    'RECORDSET_VACIO': 'No matches found',

    'menu_alumnograduacion': 'Graduation students',
    'menu_articulo': 'Scientific articles',
    'menu_ubicacion': 'Site locations',

    'text_titulo_page_alumnograduacion': 'Graduation students management',
    'text_contenido_titulo_form_alumnograduacion_ADD': 'Create graduation student',
    'text_contenido_titulo_form_alumnograduacion_EDIT': 'Update graduation student',
    'text_contenido_titulo_form_alumnograduacion_DELETE': 'Delete graduation student',
    'text_contenido_titulo_form_alumnograduacion_SHOWCURRENT': 'Graduation student detail',
    'text_contenido_titulo_form_alumnograduacion_SEARCH': 'Search graduation students',

    'label_dni_alumno': 'Student ID',
    'label_cod_titulacion': 'Degree code',
    'label_nombre_trabajo': 'Project title',
    'label_anio_academico': 'Academic year',
    'label_nota_final': 'Final grade',
    'label_tutor_principal': 'Main supervisor',
    'label_fecha_defensa': 'Defense date',
    'label_memoria_pdf': 'Submitted report',
    'label_nuevo_memoria_pdf': 'Report file (PDF)',

    'dni_alumno_min_size_KO': 'The ID must contain 9 characters.',
    'dni_alumno_max_size_KO': 'The ID must contain exactly 9 characters.',
    'dni_alumno_format_KO': 'The ID format is not valid.',
    'dni_alumno_letter_KO': 'The control letter of the ID is not valid.',
    'cod_titulacion_min_size_KO': 'The degree code must contain at least 3 characters.',
    'cod_titulacion_max_size_KO': 'The degree code cannot exceed 10 characters.',
    'cod_titulacion_format_KO': 'The degree code only allows capital letters and digits.',
    'nombre_trabajo_min_size_KO': 'The project title must contain at least 5 characters.',
    'nombre_trabajo_max_size_KO': 'The project title cannot exceed 100 characters.',
    'nombre_trabajo_format_KO': 'The project title only allows letters, digits and basic symbols.',
    'anio_academico_format_KO': 'The academic year must follow the YYYY-YYYY format.',
    'anio_academico_range_KO': 'The second academic year must be the following year.',
    'nota_final_format_KO': 'The grade must be a number with up to two decimals.',
    'nota_final_range_KO': 'The grade must be between 0 and 10.',
    'tutor_principal_min_size_KO': 'The supervisor must contain at least 4 characters.',
    'tutor_principal_max_size_KO': 'The supervisor cannot exceed 60 characters.',
    'tutor_principal_format_KO': 'The supervisor only allows letters and spaces.',
    'fecha_defensa_format_KO': 'The date must follow the dd/mm/yyyy format.',
    'fecha_defensa_value_KO': 'The provided date is not valid.',
    'nuevo_memoria_pdf_not_exist_file_KO': 'The report file is required.',
    'nuevo_memoria_pdf_type_file_KO': 'The report must be a PDF file.',
    'nuevo_memoria_pdf_max_size_file_KO': 'The report file exceeds the 5MB limit.',
    'nuevo_memoria_pdf_format_name_file_KO': 'The report file name only allows letters, digits, hyphen and dot.',

    'text_titulo_page_articulo': 'Scientific articles management',
    'text_contenido_titulo_form_articulo_ADD': 'Create article',
    'text_contenido_titulo_form_articulo_EDIT': 'Update article',
    'text_contenido_titulo_form_articulo_DELETE': 'Delete article',
    'text_contenido_titulo_form_articulo_SHOWCURRENT': 'Article detail',
    'text_contenido_titulo_form_articulo_SEARCH': 'Search articles',

    'label_CodigoA': 'Article code',
    'label_AutoresA': 'Authors',
    'label_TituloA': 'Article title',
    'label_TituloR': 'Journal title',
    'label_ISSN': 'ISSN',
    'label_VolumenR': 'Volume',
    'label_PagIniA': 'First page',
    'label_PagFinA': 'Last page',
    'label_FechaPublicacionR': 'Publication date',
    'label_FicheropdfA': 'PDF file',
    'label_nuevo_FicheropdfA': 'Upload PDF',
    'label_EstadoA': 'Process status',

    'CodigoA_min_size_KO': 'The article code is required.',
    'CodigoA_format_KO': 'The article code only allows digits.',
    'AutoresA_min_size_KO': 'At least one author must be provided.',
    'AutoresA_max_size_KO': 'Authors cannot exceed 200 characters.',
    'AutoresA_format_KO': 'Authors only allow letters, spaces, commas and dots.',
    'TituloA_min_size_KO': 'The article title is required.',
    'TituloA_max_size_KO': 'The article title cannot exceed 100 characters.',
    'TituloA_format_KO': 'The article title contains invalid characters.',
    'TituloR_min_size_KO': 'The journal title is required.',
    'TituloR_max_size_KO': 'The journal title cannot exceed 100 characters.',
    'TituloR_format_KO': 'The journal title contains invalid characters.',
    'ISSN_min_size_KO': 'The ISSN must contain 9 characters.',
    'ISSN_format_KO': 'The ISSN must follow the 0000-000X format.',
    'VolumenR_min_size_KO': 'The journal volume is required.',
    'VolumenR_format_KO': 'The volume only allows up to four digits.',
    'PagIniA_min_size_KO': 'The first page is required.',
    'PagIniA_format_KO': 'The first page only allows digits.',
    'PagFinA_min_size_KO': 'The last page is required.',
    'PagFinA_format_KO': 'The last page only allows digits.',
    'PagFinA_range_KO': 'The last page must be equal or greater than the first page.',
    'FechaPublicacionR_format_KO': 'The date must follow the dd/mm/yyyy format.',
    'FechaPublicacionR_value_KO': 'The provided date is not valid.',
    'EstadoA_value_KO': 'Select a valid status.',
    'nuevo_FicheropdfA_not_exist_file_KO': 'The article PDF is required.',
    'nuevo_FicheropdfA_type_file_KO': 'The article file must be a PDF.',
    'nuevo_FicheropdfA_max_size_file_KO': 'The article file exceeds the 5MB limit.',
    'nuevo_FicheropdfA_format_name_file_KO': 'The article file name only allows letters, digits, hyphen and dot.',

    'text_titulo_page_ubicacion': 'Sites management',
    'text_contenido_titulo_form_ubicacion_ADD': 'Create site',
    'text_contenido_titulo_form_ubicacion_EDIT': 'Update site',
    'text_contenido_titulo_form_ubicacion_DELETE': 'Delete site',
    'text_contenido_titulo_form_ubicacion_SHOWCURRENT': 'Site detail',
    'text_contenido_titulo_form_ubicacion_SEARCH': 'Search sites',

    'label_id_site': 'Identifier',
    'label_site_latitud': 'Latitude (WGS84)',
    'label_site_longitud': 'Longitude (WGS84)',
    'label_site_altitude': 'Altitude (m)',
    'label_site_locality': 'Locality',
    'label_site_provider_login': 'Provider login',
    'label_site_north_photo': 'North photo',
    'label_site_south_photo': 'South photo',
    'label_site_east_photo': 'East photo',
    'label_site_west_photo': 'West photo',
    'label_nuevo_site_north_photo': 'Upload north photo',
    'label_nuevo_site_south_photo': 'Upload south photo',
    'label_nuevo_site_east_photo': 'Upload east photo',
    'label_nuevo_site_west_photo': 'Upload west photo',

    'id_site_format_KO': 'The identifier must be numeric.',
    'site_latitud_format_KO': 'Latitude must be a decimal number with up to six decimals.',
    'site_latitud_range_KO': 'Latitude must be between -90 and 90 degrees.',
    'site_longitud_format_KO': 'Longitude must be a decimal number with up to six decimals.',
    'site_longitud_range_KO': 'Longitude must be between -180 and 180 degrees.',
    'site_altitude_format_KO': 'Altitude must be an integer number.',
    'site_altitude_range_KO': 'Altitude must be between -500 and 9000 metres.',
    'site_locality_min_size_KO': 'The locality must contain at least 3 characters.',
    'site_locality_max_size_KO': 'The locality cannot exceed 40 characters.',
    'site_locality_format_KO': 'The locality only allows letters, spaces and hyphen.',
    'site_provider_login_min_size_KO': 'The login must contain at least 3 characters.',
    'site_provider_login_max_size_KO': 'The login cannot exceed 30 characters.',
    'site_provider_login_format_KO': 'The login only allows letters, digits, hyphen and underscore.',
    'nuevo_site_north_photo_not_exist_file_KO': 'North photo is required.',
    'nuevo_site_north_photo_type_file_KO': 'North photo must be JPG or PNG.',
    'nuevo_site_north_photo_max_size_file_KO': 'North photo exceeds the 5MB limit.',
    'nuevo_site_north_photo_format_name_file_KO': 'North photo name only allows letters, digits, hyphen and dot.',
    'nuevo_site_south_photo_not_exist_file_KO': 'South photo is required.',
    'nuevo_site_south_photo_type_file_KO': 'South photo must be JPG or PNG.',
    'nuevo_site_south_photo_max_size_file_KO': 'South photo exceeds the 5MB limit.',
    'nuevo_site_south_photo_format_name_file_KO': 'South photo name only allows letters, digits, hyphen and dot.',
    'nuevo_site_east_photo_not_exist_file_KO': 'East photo is required.',
    'nuevo_site_east_photo_type_file_KO': 'East photo must be JPG or PNG.',
    'nuevo_site_east_photo_max_size_file_KO': 'East photo exceeds the 5MB limit.',
    'nuevo_site_east_photo_format_name_file_KO': 'East photo name only allows letters, digits, hyphen and dot.',
    'nuevo_site_west_photo_not_exist_file_KO': 'West photo is required.',
    'nuevo_site_west_photo_type_file_KO': 'West photo must be JPG or PNG.',
    'nuevo_site_west_photo_max_size_file_KO': 'West photo exceeds the 5MB limit.',
    'nuevo_site_west_photo_format_name_file_KO': 'West photo name only allows letters, digits, hyphen and dot.'
};
